# Generated by Django 4.2.30 on 2026-04-12 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('security_hash', models.CharField(editable=False, max_length=64)),
                ('cereal_type', models.CharField(max_length=30)),
                ('quantity_bags', models.IntegerField()),
                ('quantity_mt', models.DecimalField(decimal_places=3, max_digits=8)),
                ('storage_start_date', models.DateField()),
                ('storage_end_date', models.DateField()),
                ('total_fee_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='bookings.booking')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
