# Generated by Django 4.2.30 on 2026-04-12 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cereal_type', models.CharField(max_length=30)),
                ('quantity_bags', models.IntegerField()),
                ('quantity_mt', models.DecimalField(decimal_places=3, max_digits=8)),
                ('remaining_bags', models.IntegerField()),
                ('remaining_mt', models.DecimalField(decimal_places=3, max_digits=8)),
                ('status', models.CharField(choices=[('stored', 'In Storage'), ('partial_withdrawn', 'Partially Withdrawn'), ('fully_withdrawn', 'Fully Withdrawn'), ('spoiled', 'Spoiled/Condemned')], default='stored', max_length=30)),
                ('date_stored', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_record', to='bookings.booking')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-date_stored'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Inbound (Deposit)'), ('out', 'Outbound (Withdrawal)'), ('adjust', 'Adjustment')], max_length=10)),
                ('bags_moved', models.IntegerField()),
                ('mt_moved', models.DecimalField(decimal_places=3, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
