# Generated by Django 4.2.30 on 2026-04-12 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('inventory', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bags_to_withdraw', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mt_to_withdraw', models.DecimalField(decimal_places=3, max_digits=8)),
                ('scheduled_date', models.DateField()),
                ('actual_withdrawal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('farmer_notes', models.TextField(blank=True)),
                ('operator_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='bookings.booking')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('inventory_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='inventory.inventoryrecord')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
