# Generated by Django 4.2.30 on 2026-04-12 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('county', models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita-Taveta', 'Taita-Taveta'), ('Tana River', 'Tana River'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_capacity_mt', models.DecimalField(decimal_places=2, help_text='Total capacity in metric tonnes', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('available_capacity_mt', models.DecimalField(decimal_places=2, help_text='Currently available capacity in metric tonnes', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_type', models.CharField(choices=[('bulk', 'Bulk Storage'), ('bagged', 'Bagged Storage'), ('both', 'Bulk & Bagged'), ('hermetic', 'Hermetic Bags/Silos'), ('cold', 'Cold Storage')], default='bagged', max_length=20)),
                ('certification_status', models.CharField(choices=[('ncpb', 'NCPB Certified'), ('wrsc', 'WRSC Certified'), ('both', 'NCPB & WRSC Certified'), ('pending', 'Certification Pending'), ('none', 'Not Certified')], default='wrsc', max_length=20)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('has_pest_control', models.BooleanField(default=True)),
                ('has_moisture_control', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=True)),
                ('has_fumigation', models.BooleanField(default=False)),
                ('accepts_wrs', models.BooleanField(default=True, verbose_name='Accepts WRS Receipts')),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('storage_fee_per_bag_month', models.DecimalField(decimal_places=2, default=50.0, help_text='KES per 90kg bag per month', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='warehouses/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouses.warehouse')),
            ],
        ),
    ]
