# Generated by Django 4.2.30 on 2026-04-12 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cereal_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat'), ('sorghum', 'Sorghum'), ('millet', 'Millet'), ('barley', 'Barley'), ('rice', 'Rice'), ('beans', 'Beans'), ('peas', 'Peas'), ('other', 'Other')], default='maize', max_length=30)),
                ('quantity_bags', models.IntegerField(help_text='Number of 90kg bags', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_mt', models.DecimalField(decimal_places=3, help_text='Weight in metric tonnes (auto-calculated)', max_digits=8)),
                ('storage_start_date', models.DateField()),
                ('storage_end_date', models.DateField()),
                ('total_fee_kes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('farmer_notes', models.TextField(blank=True)),
                ('operator_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
